name: Sakaryaspor Bagis Sistemi

on:
  schedule:
    - cron: '*/15 * * * *' # Her 15 dakikada bir otomatik Ã§alÄ±ÅŸÄ±r
  workflow_dispatch: # Manuel seÃ§im butonunu aktif eder
    inputs:
      islem_tipi:
        description: 'Yapilacak islemi secin'
        required: true
        default: 'yeni_takip'
        type: choice
        options:
        - yeni_takip
        - tum_listeyi_zip_yap

jobs:
  calistir:
    runs-on: ubuntu-latest
    steps:
      - name: Depoyu Cek
        uses: actions/checkout@v3

      - name: Python Kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Kutuphaneleri Yukle
        # HatalarÄ± Ã¶nlemek iÃ§in bs4 ve lxml buraya eklendi
        run: |
          pip install Pillow requests beautifulsoup4 lxml

      - name: Botu Yonet
        env:
          MAIL_ADRESI: ${{ secrets.MAIL_ADRESI }}
          MAIL_SIFRESI: ${{ secrets.MAIL_SIFRESI }}
          ALICI_MAIL: ${{ secrets.ALICI_MAIL }}
        run: |
          if [ "${{ github.event.inputs.islem_tipi }}" == "tum_listeyi_zip_yap" ]; then
            echo "ğŸš€ TÃ¼m liste zipleniyor..."
            python tam_liste.py
          else
            echo "ğŸ” Yeni baÄŸÄ±ÅŸÃ§Ä±lar taranÄ±yor..."
            python olus.py
          fi

      - name: Degisiklikleri Kaydet
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add .
          git commit -m "Veri guncellemesi" || exit 0
          git push
