- name: Botu Yonet
        env:
          MAIL_ADRESI: ${{ secrets.MAIL_ADRESI }}
          MAIL_SIFRESI: ${{ secrets.MAIL_SIFRESI }}
          ALICI_MAIL: ${{ secrets.ALICI_MAIL }}
        run: |
          if [ "${{ github.event.inputs.islem_tipi }}" == "tum_listeyi_zip_yap" ]; then
            python tam_liste.py
          else
            python olus.py
          fi

      # DOSYAYI INDIRILEBILIR YAPMA ADIMI BURADA
      - name: Zip Dosyasini Yukle
        if: github.event.inputs.islem_tipi == 'tum_listeyi_zip_yap'
        uses: actions/upload-artifact@v4
        with:
          name: Sakaryaspor-Sertifikalar
          path: Sakaryaspor_Tum_Sertifikalar.zip
          retention-days: 5

      - name: Degisiklikleri Kaydet
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add .
          git commit -m "Hafiza guncellendi" || exit 0
          git push
